#When files get copied, the variables defined in the file will get copied as is. If we want to pass a variable value while copying the file, use template module. This will replace the variables in the file with the value of the variable that is being passed. Here, the source file is hello.txt which has a variable name. ansible-playbook 04-template.yml -e name=<name> will have no effect for copy module, whereas the variable name will be filled with the provided variable value for template module.

- name: Demo on template
  hosts: localhost
  tasks:
    - name: Copy file
      ansible.builtin.copy:
        src: hello.txt
        dest: /tmp/h1.txt

    - name: Template file
      ansible.builtin.template:
        src: hello.txt
        dest: /tmp/h2.txt

