- name: Loops Demo
  hosts: localhost
  tasks:
    - name: Print
      ansible.builtin.debug:
        msg: "Fruit - {{ item}}"
      loop:
        - apple
        - banana
        - orange

    - name: Print with quantity
      ansible.builtin.debug:
        msg: "Fruit - {{ item['name'] }}, Quantity - {{ item.quantity }}"
      loop:
        - { name: apple, quantity: 100}
        - { name: banana, quantity: 200}
        - { name: orange, quantity: 300}

