- name: Loops Demo
  hosts: localhost
  tasks:
    - name: Print
      ansible.builtin.debug:
        msg: "Fruit - {{ item}}" #item is a variable that can be used for loop
      loop:
        - apple
        - banana
        - orange

    - name: Print with quantity
      ansible.builtin.debug:
        msg: "Fruit - {{ item['name'] }}, Quantity - {{ item.quantity }}"
        #two different ways to call. item.quantity or item['quantity']
      loop:
        - { name: apple, quantity: 100}
        - { name: banana, quantity: 200}
        - { name: orange, quantity: 300}

