#https://docs.ansible.com/ansible/2.9/plugins/lookup/hashi_vault.html
# vault_token will be passed in cli during execution

- name: retrieve secrets
  hosts: localhost
  tasks:
    - debug:
        msg: "{{ lookup('hashi_vault', 'secret=kv/data/test:MYPASS token={{vault_token}} url=https://vault-internal.sridevops.site:8200 validate_certs=false')}}"

        #kv - key/value engine in vault
        #test - secret
        #MYPASS - key

# use ansible-playbook 09-hashicorp-vault.yml -e vault_token=<token value> to execute
# above lookup command is modified and used in roboshop_ansible repo as well
# after lookup, secrets are exported as env variables. notice that we are only replacing env variables across the repos
