- name: retrive secrets
  hosts: localhost
  tasks:
    - debug:
        msg: "{{ lookup('hashi_vault', 'secret=kv/data/test:MYPASS token={{vault_token}} url=https://vault-internal.rdevopsb79.online:8200 validate_certs=false')}}"

